logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/ec2-user/app/log
  file:
    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/david3?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: david3
    password: jesus
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://dev-api.daddyprogrammer.org
